[project]
name = "fsm-qa-mcp-server"
version = "0.1.0"
description = "Minimal FastMCP server for FSM QA tools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.12.0",
    "mcp>=1.13.1",
    "pymysql>=1.1.2",
]
